### ISSUE TITLE
As a developer, i want github to automatically move issues in our project board when jobs are done on the linked branches

### ISSUE THREAD

**Issue by Emil860m** [ITU-BDSA23-GROUP24/Chirp#15]
## Success criteria

- [ ] When an issue is linked with a branch, the issue should be moved to "In Progress"
- [ ] When a pull request from a branch linked with an issue to development is created, move the issue to "In Review"
- [ ] If a pull request is denied or changes requested, the issue should be moved back to "In Progress"
- [ ] When a pull request is approved and merged, the issue should be moved to "Done"
- [ ] When a pull request and merge from development to main is approved and merged, all issues in done should be archived

**Comment by FrBB-ITU** [comment]
Cannot be solved as we don't have a paying github organization...
