### ISSUE TITLE
As a user, it is currently impossible to get help with the --help command, which is bad for the user experience

### ISSUE THREAD

**Issue by OskarsGit** [ITU-BDSA23-GROUP24/Chirp#19]
When running the program with "dotnet run -h" or "dotnet run --help", the help provided is for "dotnet run", not for our program. This does not seem to be an issue with the automatically created commands from docopt, as --version works perfectly well. The issue persists even when writing "dotnet run chirp -h". 

## Success Criteria
???

**Comment by FrBB-ITU** [comment]
This now works if you create a single executable, and run Chirp from that

**Comment by FrBB-ITU** [comment]
This now works if you create a single executable, and run Chirp from that
